# 
# docker-compose -f docker-compose-blue.yml up
# docker-compose -f docker-compose-blue.yml down
# 

# docker build --progress=plain --no-cache -t @maryline/blue:0.0.1 -f apps/api/Dockerfile.blue .

# psql -U user -d mydatabase
# \dt

version: '3.8'

services:
  db:
    container_name: blue_database
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: blue_api
    build:
      context: .
      dockerfile: apps/api/Dockerfile.blue
    environment:
      NODE_ENV: development
      PORT: 3001
      GOOGLE_CALLBACK_URL: http://localhost:3001/api/auth/google/redirect
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_NAME: mydatabase
      DATABASE_PASSWORD: password
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
      CLERK_ISSUER_URL: https://hardy-weasel-66.clerk.accounts.dev
      MEILI_HOST: http://meilisearch:7700
    secrets:
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - JWT_SECRET
      - JWT_EXPIRATION_TIME
      - AT_SECRET
      - RT_SECRET
      - MEILI_KEY
    depends_on:
      - db
    ports:
      - "3001:3001"

volumes:
  pgdata:

secrets:
  GOOGLE_CLIENT_ID:
    file: ./secrets/GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET:
    file: ./secrets/GOOGLE_CLIENT_SECRET
  JWT_SECRET:
    file: ./secrets/JWT_SECRET
  JWT_EXPIRATION_TIME:
    file: ./secrets/JWT_EXPIRATION_TIME
  AT_SECRET:
    file: ./secrets/AT_SECRET
  RT_SECRET:
    file: ./secrets/RT_SECRET
  MEILI_KEY:
    file: ./secrets/MEILI_KEY
