# docker-compose up --build

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '3001:3000'
    environment:
      NODE_ENV: production
      PORT: 3001
      GOOGLE_CALLBACK_URL: http://localhost:3001/api/auth/google/redirect
      # TODO: DELETE
      # DATABASE_URL: postgresql://developer:developer@localhost:5432/chevere?schema=public
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: developer
      DATABASE_NAME: chevere
      CLERK_ISSUER_URL: https://hardy-weasel-66.clerk.accounts.dev
      MEILI_HOST: http://meilisearch:7700
    secrets:
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - DATABASE_PASSWORD
      - JWT_SECRET
      - JWT_EXPIRATION_TIME
      - AT_SECRET
      - RT_SECRET
      - MEILI_KEY

secrets:
  GOOGLE_CLIENT_ID:
    file: ./secrets/GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET:
    file: ./secrets/GOOGLE_CLIENT_SECRET
  DATABASE_PASSWORD:
    file: ./secrets/DATABASE_PASSWORD
  JWT_SECRET:
    file: ./secrets/JWT_SECRET
  JWT_EXPIRATION_TIME:
    file: ./secrets/JWT_EXPIRATION_TIME
  AT_SECRET:
    file: ./secrets/AT_SECRET
  RT_SECRET:
    file: ./secrets/RT_SECRET
  MEILI_KEY:
    file: ./secrets/MEILI_KEY



# services:
#   api:
#     build:
#       context: .
#       dockerfile: apps/web/Dockerfile
#     ports:
#       - '3001:3000'


#     restart: always
#     # ports:
#     #   - "80:80"
#     #   - "443:443"
#     # volumes:
#     #   - ./dist:/app/dist
#     #   - ./nginx.conf:/etc/nginx/nginx.conf
#       # - ./certbot/conf:/etc/letsencrypt
#       # - ./certbot/www:/var/www/certbot
#     environment:
#       NODE_ENV: production
#       PORT: 3001
#       GOOGLE_CALLBACK_URL: http://localhost:3001/api/auth/google/redirect
#       DATABASE_URL: postgresql://developer:dummy_password@localhost:5432/chevere?schema=public
#       DATABASE_HOST: localhost
#       DATABASE_PORT: 5432
#       DATABASE_USER: developer
#       DATABASE_NAME: chevere
#       CLERK_ISSUER_URL: https://hardy-weasel-66.clerk.accounts.dev
#       MEILISEARCH_URL: http://meilisearch:7700
#     secrets:
#       - GOOGLE_CLIENT_ID
#       - GOOGLE_CLIENT_SECRET
#       - DATABASE_PASSWORD
#       - JWT_SECRET
#       - JWT_EXPIRATION_TIME
#       - AT_SECRET
#       - RT_SECRET
#       - MEILI_KEY

#   # certbot:
#   #   image: certbot/certbot
#   #   volumes:
#   #     - ./certbot/conf:/etc/letsencrypt
#   #     - ./certbot/www:/var/www/certbot
#   #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

# secrets:
#   GOOGLE_CLIENT_ID:
#     file: ./secrets/GOOGLE_CLIENT_ID
#   GOOGLE_CLIENT_SECRET:
#     file: ./secrets/GOOGLE_CLIENT_SECRET
#   DATABASE_PASSWORD:
#     file: ./secrets/DATABASE_PASSWORD
#   JWT_SECRET:
#     file: ./secrets/JWT_SECRET
#   JWT_EXPIRATION_TIME:
#     file: ./secrets/JWT_EXPIRATION_TIME
#   AT_SECRET:
#     file: ./secrets/AT_SECRET
#   RT_SECRET:
#     file: ./secrets/RT_SECRET
#   MEILI_KEY:
#     file: ./secrets/MEILI_KEY










# services:
#   api:
#     build: .
#     restart: always
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./dist:/app/dist
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - ./certbot/conf:/etc/letsencrypt
#       - ./certbot/www:/var/www/certbot
#     environment:
#       - NODE_ENV=production

#   certbot:
#     image: certbot/certbot
#     volumes:
#       - ./certbot/conf:/etc/letsencrypt
#       - ./certbot/www:/var/www/certbot
#     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"



# services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: apps/web/Dockerfile
  #   ports:
  #     - '3000:3000'
  #   # environment:
  #   #   - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
  #   #   - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
  #   # depends_on:
  #   #   - api
  #   #   - meilisearch
  #   #   - postgres

  # api:
  #   build:
  #     context: .
  #     dockerfile: apps/api/Dockerfile
  #   ports:
  #     - '3001:3000'
    # environment:
    #   - DATABASE_URL=postgres://myuser:mypassword@postgres:5432/mydatabase
    #   - MEILISEARCH_URL=http://meilisearch:7700
    # depends_on:
    #   - postgres
    #   - meilisearch

#   meilisearch:
#     image: getmeili/meilisearch:v0.28.1
#     ports:
#       - '7700:7700'
#     volumes:
#       - meili_data:/meili_data

#   postgres:
#     image: postgres:13-alpine
#     environment:
#       POSTGRES_DB: mydatabase
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
#     ports:
#       - '5432:5432'
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   meili_data:
#   postgres_data:
