version: '3.8'
services:
  web:
    build:
      context: ./apps/web
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    depends_on:
      - api
      - meilisearch
      - postgres

  api:
    build:
      context: ./apps/api
    ports:
      - '3001:3000'
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@postgres:5432/mydatabase
      - MEILISEARCH_URL=http://meilisearch:7700
    depends_on:
      - postgres
      - meilisearch

  meilisearch:
    image: getmeili/meilisearch:v0.28.1
    ports:
      - '7700:7700'
    volumes:
      - meili_data:/meili_data

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  meili_data:
  postgres_data:
