version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: developer
      POSTGRES_DB: chevere
      POSTGRES_PASSWORD: developer
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  meilisearch:
    image: getmeili/meilisearch:v0.28.1
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: developer
      DATABASE_NAME: chevere
      DATABASE_PASSWORD: developer
      DATABASE_URL: postgres://developer:developer@postgres:5432/chevere?schema=public
      CLERK_ISSUER_URL: https://hardy-weasel-66.clerk.accounts.dev
      MEILI_HOST: http://meilisearch:7700
    depends_on:
      - postgres
      - meilisearch
    secrets:
      - DATABASE_PASSWORD
      - JWT_SECRET
      - JWT_EXPIRATION_TIME
      - AT_SECRET
      - RT_SECRET
      - MEILI_KEY

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_aGFyZHktd2Vhc2VsLTY2LmNsZXJrLmFjY291bnRzLmRldiQ
    depends_on:
      - api
      - meilisearch
      - postgres
    secrets:
      - CLERK_SECRET_KEY

volumes:
  postgres_data:
  meili_data:

secrets:
  DATABASE_PASSWORD:
    file: ./secrets/DATABASE_PASSWORD
  JWT_SECRET:
    file: ./secrets/JWT_SECRET
  JWT_EXPIRATION_TIME:
    file: ./secrets/JWT_EXPIRATION_TIME
  AT_SECRET:
    file: ./secrets/AT_SECRET
  RT_SECRET:
    file: ./secrets/RT_SECRET
  MEILI_KEY:
    file: ./secrets/MEILI_KEY
  CLERK_SECRET_KEY:
    file: ./secrets/CLERK_SECRET_KEY
