#
# docker-compose down -v
# docker build --progress=plain --no-cache -t api-dev -f apps/api/Dockerfile.dev .
# 

# Stage 1: Build the application
FROM node:18-alpine AS build

WORKDIR /app

ADD package*.json .
ADD apps/api/prisma/schema.prisma ./prisma/

RUN npm install

COPY . .

# Build the application
# RUN npx nx build api --configuration=production
RUN npx nx build api --configuration=development

# Stage 2: Setup the application
FROM node:18-alpine

WORKDIR /app

# Copy built application and dependencies from the build stage
COPY --from=build /app/dist/apps/api /app/dist/apps/api
COPY --from=build /app/package*.json /app/
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/prisma /app/prisma
COPY --from=build /app/nx.json /app

# Expose the port the app runs on
EXPOSE 3000

# CMD ["npm", "run", "start:migrate:prod"]
CMD ["npm", "run", "start:migrate"]
