# name: CI

# on:
#   push:
#     branches:
#       - main
#   pull_request:

# permissions:
#   actions: read
#   contents: read

# jobs:
#   main:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [20.x]


#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: Install Nest cli
#         run: yarn global add @nestjs/cli 

#       - name: Install Nx cli
#         run: yarn global add nx@latest

#       - name: Install dependencies
#         run: yarn install

#       - name: Build
#         run: yarn run nx run api:build

#       # - run: yarn install
#       # - uses: nrwl/nx-set-shas@v4


#       - name: Run Nx affected
#         run: yarn run nx affected -t build

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Nest cli
        run: yarn global add @nestjs/cli         

      - name: Install Nx cli
        run: yarn global add nx@latest

      - name: Install dependencies
        working-directory: apps/api
        run: yarn install

      - name: Build
        working-directory: apps/api
        run: yarn build

      - name: Run Nx affected
        run: yarn run nx affected -t build
