name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
            
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Print environment variables
        run: |
          echo "Printing environment variables..."
          env

      - name: Check Nx version
        run: |
          echo "Checking Nx version..."
          npx nx --version

      - name: Check Node.js version
        run: |
          echo "Checking Node.js version..."
          node --version

      - name: Check Yarn version
        run: |
          echo "Checking Yarn version..."
          yarn --version
            
      - name: Build
        working-directory: apps/api
        env:
          PATH: ./node_modules/.bin:$PATH
        run: |
          echo "Running build with verbose logging..."
          npx nx run api:build --verbose

      - name: Run Nx affected
        env:
          PATH: ./node_modules/.bin:$PATH
        run: |
          echo "Running Nx affected..."
          npx nx affected -t build --verbose
