name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "build" targets have been requested
      # - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Set Nx SHAs
        uses: nrwl/nx-set-shas@v4

      - name: Install Nest CLI
        run: npm install -g @nestjs/cli

      - name: Check Nx version
        run: npx nx --version

      - name: Check Node.js version
        run: node --version

      - name: Check npm version
        run: npm --version

      - name: Check Nest version
        run: nest --version

      - name: Install the dependencies
        run: npm install

      - name: Install @nx/nx-linux-x64-gnu needed by this CI
        run: npm install @nx/nx-linux-x64-gnu@19.4.0

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      - run: npx nx affected --base=main --head=HEAD -t build
