name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Set Nx SHAs
        uses: nrwl/nx-set-shas@v4

      - name: Install Nest CLI
        run: npm install -g @nestjs/cli
        
      - name: Install Biome
        run: npm install -g biome

      - name: Check Nx version
        run: npx nx --version

      - name: Check Node.js version
        run: node --version

      - name: Check npm version
        run: npm --version

      - name: Check Nest version
        run: nest --version

      - name: Check Biome version
        run: npx biome --version

      - name: Install the dependencies
        run: npm install --include=optional

      - name: Biome checks
        run: npx biome format --write . && biome lint --write . && biome check --write .

      - name: Run Nx affected commands
        run: npx nx affected --base=main --head=HEAD -t build
