name: Database CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  migrations:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Generates the Prisma Client based schema definition in schema.prisma
        run: npx prisma generate --schema apps/api/prisma/schema.prisma

      - name: Run database migrations
        env:
          DATABASE_URL: postgres://myuser:mypassword@localhost:5432/mydatabase
        run: npx prisma migrate deploy
