# https://docs.github.com/en/actions
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

name: 01-nextjs-app CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: 01-nextjs-app

      - name: Build
        run: npm run build
        working-directory: 01-nextjs-app

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: 01-nextjs-app
          file: 01-nextjs-app/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/docker-monster-zero-one-nextjs-app:latest
          build-args: |
            TAG_ID: ${{ secrets.TAG_ID }}
